// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adimwbhbfzmlirfrlcys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkaW13YmhiZnptbGlyZnJsY3lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4OTE4NjksImV4cCI6MjA2MTQ2Nzg2OX0.0IAT04DgBgG5WDRFg5MVY0hwA5AX4D-kOHBrL627cEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);